eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangpeng849/SpringcloudConfig
          basedir: H:/studycloud/config/basedir
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
